fix installer on intel motherboard xeon server raid
```python
name = re.match("([^_]*)(_\d+)?$", name).group(1)
```
Throws: `AttributeError: 'NoneType' object has no attribute 'groups'` because sometimes there are more than numbers after the '_'.